{
 "title": "HTTP Check",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "endpoint", "query": { "query": "httpcheck_duration" } }
  ]
 },
 "panels": [
  {
   "title": "httpcheck_duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(http_url) (httpcheck_duration{http_url=~\"$endpoint\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "httpcheck_status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(http_status_class, http_url) (httpcheck_status{http_url=~\"$endpoint\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "httpcheck_error",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "httpcheck_error", "legendFormat": "{{error_message}}" }
   ]
  }
 ]
}